from __future__ import annotations


FIELD_CATALOG: dict[str, dict[str, str]] = {
    "message.sending_company_in": {"label": "SendingCompanyIN", "required": "nao"},
    "message.transmitting_country": {"label": "TransmittingCountry", "required": "sim"},
    "message.receiving_country": {"label": "ReceivingCountry", "required": "sim"},
    "message.message_ref_id": {"label": "MessageRefId", "required": "sim"},
    "message.message_type_indic": {"label": "MessageTypeIndic CRS", "required": "crs"},
    "message.corr_message_ref_id": {"label": "CorrMessageRefId", "required": "condicional"},
    "message.reporting_period": {"label": "ReportingPeriod", "required": "sim"},
    "message.timestamp": {"label": "Timestamp", "required": "sim"},
    "message.warning": {"label": "Warning", "required": "nao"},
    "message.contact": {"label": "Contact", "required": "nao"},
    "reporting_fi.name": {"label": "ReportingFI Nome", "required": "sim"},
    "reporting_fi.in": {"label": "ReportingFI IN/TIN/GIIN", "required": "nao"},
    "reporting_fi.issued_by": {"label": "ReportingFI IN/TIN IssuedBy", "required": "nao"},
    "reporting_fi.res_country": {"label": "ReportingFI Pais residencia", "required": "nao"},
    "reporting_fi.address_country": {"label": "ReportingFI Pais endereco", "required": "sim"},
    "reporting_fi.address_free": {"label": "ReportingFI Endereco livre", "required": "sim"},
    "reporting_fi.doc_type_indic": {"label": "ReportingFI DocTypeIndic", "required": "sim"},
    "reporting_fi.doc_ref_id": {"label": "ReportingFI DocRefId", "required": "sim"},
    "reporting_fi.filer_category": {"label": "FATCA FilerCategory", "required": "fatca"},
    "account.doc_type_indic": {"label": "Account DocTypeIndic", "required": "sim"},
    "account.doc_ref_id": {"label": "Account DocRefId", "required": "sim"},
    "account.account_number": {"label": "AccountNumber", "required": "sim"},
    "account.account_number_type": {"label": "AccountNumberType", "required": "nao"},
    "account.closed": {"label": "ClosedAccount", "required": "nao"},
    "account.balance": {"label": "AccountBalance", "required": "sim"},
    "account.currency": {"label": "Currency", "required": "sim"},
    "account.crs_dd_procedure": {"label": "CRS DDProcedure", "required": "crs"},
    "account.crs_account_type": {"label": "CRS AccountType", "required": "crs"},
    "account.crs_joint_account_number": {"label": "CRS JointAccount Number", "required": "nao"},
    "holder.kind": {"label": "Tipo titular individual/organisation", "required": "sim"},
    "holder.first_name": {"label": "FirstName titular", "required": "individual"},
    "holder.last_name": {"label": "LastName titular", "required": "individual"},
    "holder.organisation_name": {"label": "Nome organizacao titular", "required": "organisation"},
    "holder.res_country": {"label": "Residencia fiscal titular", "required": "sim"},
    "holder.tin": {"label": "TIN/IN titular", "required": "nao"},
    "holder.tin_issued_by": {"label": "TIN/IN IssuedBy titular", "required": "nao"},
    "holder.birth_date": {"label": "Data de nascimento titular", "required": "nao"},
    "holder.address_type": {"label": "Tipo de endereco titular", "required": "nao"},
    "holder.address_country": {"label": "Pais endereco titular", "required": "sim"},
    "holder.address_free": {"label": "Endereco titular", "required": "sim"},
    "holder.acct_holder_type": {"label": "AcctHolderType", "required": "organisation"},
    "holder.crs_self_cert": {"label": "CRS SelfCert titular", "required": "crs"},
    "fatca.us_tin": {"label": "FATCA US Tax ID", "required": "condicional"},
    "fatca.us_tin_issued_by": {"label": "FATCA pais emissor do US Tax ID", "required": "condicional"},
    "fatca.us_tin_status": {"label": "FATCA status do US Tax ID", "required": "condicional"},
    "fatca.us_tin_reason": {"label": "FATCA motivo da ausencia do US Tax ID", "required": "condicional"},
    "fatca.us_tin_source": {"label": "FATCA origem da informacao do US Tax ID", "required": "nao"},
    "fatca.missing_us_tin_policy": {"label": "FATCA politica para US Tax ID ausente", "required": "condicional"},
    "payment.type": {"label": "Payment Type", "required": "nao"},
    "payment.amount": {"label": "Payment Amount", "required": "nao"},
    "payment.currency": {"label": "Payment Currency", "required": "nao"},
    "controlling.first_name": {"label": "CRS Controlling Person FirstName", "required": "condicional"},
    "controlling.last_name": {"label": "CRS Controlling Person LastName", "required": "condicional"},
    "controlling.res_country": {"label": "CRS Controlling Person residência", "required": "condicional"},
    "controlling.tin": {"label": "CRS Controlling Person TIN", "required": "nao"},
    "controlling.tin_issued_by": {"label": "CRS Controlling Person TIN IssuedBy", "required": "nao"},
    "controlling.address_country": {"label": "CRS Controlling Person país endereço", "required": "condicional"},
    "controlling.address_free": {"label": "CRS Controlling Person endereço", "required": "condicional"},
    "controlling.type": {"label": "CRS ControllingPersonType", "required": "condicional"},
    "controlling.self_cert": {"label": "CRS Controlling Person SelfCert", "required": "condicional"},
    "substantial.kind": {"label": "FATCA Substantial Owner tipo", "required": "condicional"},
    "substantial.first_name": {"label": "FATCA Substantial Owner FirstName", "required": "condicional"},
    "substantial.last_name": {"label": "FATCA Substantial Owner LastName", "required": "condicional"},
    "substantial.organisation_name": {"label": "FATCA Substantial Owner organização", "required": "condicional"},
    "substantial.res_country": {"label": "FATCA Substantial Owner residência", "required": "condicional"},
    "substantial.tin": {"label": "FATCA Substantial Owner TIN", "required": "nao"},
    "substantial.tin_issued_by": {"label": "FATCA Substantial Owner TIN IssuedBy", "required": "nao"},
    "substantial.address_country": {"label": "FATCA Substantial Owner país endereço", "required": "condicional"},
    "substantial.address_free": {"label": "FATCA Substantial Owner endereço", "required": "condicional"},
    "nil_report.enabled": {"label": "FATCA NilReport", "required": "nao"},
}


def default_profile_fields() -> list[str]:
    return list(FIELD_CATALOG.keys())
